FROM maven:3.8.7-eclipse-temurin-19-alpine

LABEL maintener="Matheus <matheus@email.com>"

WORKDIR /fitness

COPY . .

ENV DATASOURCE_USERNAME=root
ENV DATASOURCE_PASSWORD=1234

RUN mvn package

EXPOSE 8080

CMD ["java", "-jar", "target/fitness-0.0.1-SNAPSHOT.jar"]